name: EchoesOfGold
version: '1.2.2'
main: me.andrew.EchoesOfGold.EchoesOfGold
api-version: '1.21'
author: ItsAndrew
softdepend:
  - Vault

permissions:
  eog.admin:
    description: Gives access to commands
    default: op
  eog.use:
    description: Gives access to hints
    default: true

commands:
  eog:
    usage: /eog help
    description: The commands for the event
    permission: eog.admin
  hints:
    usage: /hints
    description: Allows you to access the hints
    permission: eog.use